apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJaWFpuY25WemMybGhPbWRwZEdoMVlsOXdZWFJmTVRGQlREZEJTbFpSTUZOaFkxTkZSWFJqWWtkSFZWODJjSGxPUjI4ME5Ia3hNMmRtZEVoWmJrbE9PVk5KVXpaR1R6WXpkVlpWYVVocFFqSkJSbGxCTTJOQlZEWldTRXBSVFVzeloyWlNNSE5hYkE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
